### ISSUE TITLE
No hash for some Trailblazer's avatars

### ISSUE THREAD

**Issue by Vestrond** [Vestrond/hsr-ext#2]
Currently we have no hash for some Trailblazer's avatars:
- Caelus Harmony (Imaginary)
- ~~Stelle Preservation (Fire)~~ ✅ (by [FI00ds](https://github.com/FI00ds))
- ~~Stelle Harmony (Imaginary)~~ ✅ (by [FI00ds](https://github.com/FI00ds))

Location:
`popup.js > getTrailblazerFromUrls() > const trailblazerMap`.

**Comment by Vestrond** [comment]
**How can You get a hash of avatars?**

1. Open https://act.hoyolab.com/app/community-game-records-sea/rpg/index.html#/hsr
2. Insert to the console the `getImageHash()` function from the README.
3. Copy the character avatar URL and calculate the hash using the function:
	```js
	getImageHash("<url>").then(console.log);
	```
4. Copy the result here, or to PR.

You can also just copy the links to the avatars here, and I'll calculate the hashes and do the PR myself.

Thank you all in advance for your help!

**Comment by FI00ds** [comment]
Hopefully I did this right

- Harmony Stelle
![firefox_2024-06-14_20-56-47](https://github.com/Vestrond/hsr-ext/assets/122728302/3832020c-3c6c-4efc-97ef-ceae9b427837)
- Harmony Caelus
![firefox_2024-06-14_21-00-22](https://github.com/Vestrond/hsr-ext/assets/122728302/25a11dce-147a-410f-8d78-1f1a99c15d09)
- Preservation Stelle
![firefox_2024-06-14_21-13-38](https://github.com/Vestrond/hsr-ext/assets/122728302/29b4d8cd-9a14-4442-85d1-02db565ce960)

Caelus might be wrong since I grabbed that from a different user's hoyolab character showcase, both Stelle are from my own though so should be good

**Comment by Vestrond** [comment]
Hmm, a little weird. The links are different in length from what I've seen from other characters in my browsers.

Did you use these images?

<img width="688" alt="image" src="https://github.com/Vestrond/hsr-ext/assets/7628854/701ebcb7-542b-4cbc-aede-88acf810bece">

I have links like this:

- ```https://act-webstatic.hoyoverse.com/darkmatter/hkrpg/prod_gf_cn/item_icon_u3294b/ea1036c33142ad6b86fc664e3d09be5c.png?x-oss-process=image%2Fformat%2Cwebp```

or

- ```https://act-webstatic.hoyoverse.com/darkmatter/hkrpg/prod_gf_cn/item_icon_u3294b/a8e5c612a6a97d6987fa9b69ec6666b3.png?x-oss-process=image%2Fformat%2Cwebp```

**Comment by FI00ds** [comment]
ah no I used the big images on the left

harmony stelle
![firefox_2024-06-18_23-34-58](https://github.com/Vestrond/hsr-ext/assets/122728302/51376f01-617b-46dc-b75a-02d44e1be0be)

preservation stelle
![firefox_2024-06-18_23-38-53](https://github.com/Vestrond/hsr-ext/assets/122728302/b04c33ce-742c-4f92-b0d1-01b4eadf232d)

these are using the small circle icons

**Comment by FI00ds** [comment]
harmony stelle
![firefox_2024-06-18_23-34-58](https://github.com/Vestrond/hsr-ext/assets/122728302/51376f01-617b-46dc-b75a-02d44e1be0be)

**Comment by FI00ds** [comment]
preservation stelle
![firefox_2024-06-18_23-38-53](https://github.com/Vestrond/hsr-ext/assets/122728302/b04c33ce-742c-4f92-b0d1-01b4eadf232d)

**Comment by Vestrond** [comment]
That's awesome, thank you! Now we just have to find the last one (Harmony Caelus). But I think I'll try to extract that data myself in the near future.

**Comment by Vestrond** [comment]
Done 👍
